### ISSUE TITLE
Add Route53 support

### ISSUE THREAD

**Issue by jbondhus** [certera-io/dns-client-project#1]
Please add Route53 support to this client, I'd like to use it with Certera.

**Comment by certeraio** [comment]
Hi @jbondhus! I'm so sorry for missing this. For some reason, when creating new repos, it doesn't automatically put me in as "watching". Are you still in need of Route53 or have you found a work-around?

**Comment by jbondhus** [comment]
@certeraio I'm still in need of route53 support.

**Comment by certeraio** [comment]
@jbondhus I don't have a Route53 account to test things out with, but looks like there are various clients out there you can use with Certera.

The simplest may actually be the AWS CLI itself.

After installing the AWS CLI, you can then create a script that can be used by Certera's "Setup Script" (maybe something like /opt/certera-dns/setup.sh).

In Cetera, set DNS record script
`/opt/certera-dns/setup.sh`

And also in Cetera, set script arguments to be
`{{Domain}} {{Record}} {{Value}}`

The `/opt/certera-dns/setup.sh` can look something like this:
```
#!/bin/bash

HOSTED_ZONE_ID="XXXXXXXX"

# This is the FQDN of the DNS record
# if {{Domain}} is mysite.com and {{Record}} is _acme-challenge.www.dev
# then NAME will be _acme-challenge.www.dev.mysite.com.
NAME="$2.$1."
TYPE="TXT"
TTL=600
VALUE=$3

#prepare route 53 payload
cat > /tmp/route53_changes.json << EOF
    {
      "Comment":"Updated From DDNS Shell Script",
      "Changes":[
        {
          "Action":"UPSERT",
          "ResourceRecordSet":{
            "ResourceRecords":[
              {
                "Value":"$VALUE"
              }
            ],
            "Name":"$NAME",
            "Type":"$TYPE",
            "TTL":$TTL
          }
        }
      ]
    }
EOF

#update records
aws2 route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file:///tmp/route53_changes.json >> /dev/null
```

Similarly, you'll want to create a "cleanup" script for Certera to use to make sure your TXT records aren't growing endlessly.

I hope that helps!

(Apologies if the script doesn't immediately work as I don't have a way to test it as well as I'm not 100% familiar with how Route53 sets DNS records, I may have an extra period at the end of the FQDN...)

**Comment by certeraio** [comment]
Something I found yesterday for the first time is this project: https://github.com/AnalogJ/lexicon

Had I known about it, I likely would have not created dnsc. Lexicon looks to be mature, well supported, and actively developed. I recommend using that project for Route53 capabilities.
