### ISSUE TITLE
Azure DNS TXT record is added to the same field

### ISSUE THREAD

**Issue by nomailme** [certera-io/dns-client-project#2]
Hello!

Found a bug that relates to the Azure DNS.
If we update a TXT record it updates the same field in AzureDNS while new value for the record is intended.
I have fixed it in my fork, and if you want I can make a pull request to this repository.

**Comment by certeraio** [comment]
Yes, please do submit a PR! Thank you!

**Comment by certeraio** [comment]
Hello again @nomailme!

Thank you for finding the bug and contributing a PR to fix it. I've merged your PR and issued a new release as version 1.1.1 here:  
https://github.com/certera-io/dns-client-project/releases/tag/1.1.1
